"""Add bank details to companies

Revision ID: a13ff6e72a58
Revises: 
Create Date: 2026-03-29 20:05:25.926915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a13ff6e72a58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    with op.batch_alter_table('sale_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_mycompany_invoice_number'))

    op.drop_table('sale_invoices')
    op.drop_table('payments')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('cgst',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sgst',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('igst',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_tax',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.drop_index(batch_op.f('invoice_number'))
        batch_op.drop_constraint(batch_op.f('1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['supplier_company_id'], ['id'])
        batch_op.create_foreign_key(None, 'companies', ['my_company_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('2'), 'companies', ['supplier_company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('1'), 'companies', ['my_company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('invoice_number'), ['invoice_number'], unique=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('total_tax',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('igst',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=8, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sgst',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=8, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cgst',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=8, scale=2),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_no')
        batch_op.drop_column('bank_name')

    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sale_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sale_invoices.id'], name=op.f('1')),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_unicode_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('sale_invoices',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('invoice_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('my_company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('customer_company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('cgst', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('sgst', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('igst', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_tax', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount_received', mysql.FLOAT(), nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('3')),
    sa.ForeignKeyConstraint(['customer_company_id'], ['companies.id'], name=op.f('2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['my_company_id'], ['companies.id'], name=op.f('1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_unicode_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    with op.batch_alter_table('sale_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_mycompany_invoice_number'), ['my_company_id', 'invoice_number'], unique=True)

    op.create_table('sale_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sale_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('hsn_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('taxable_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sale_invoices.id'], name=op.f('1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_unicode_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
